#!/bin/bash

flow_container_name="$1"
shift

docker_flags="--rm -it --user flow -w /var/www"

for link in $(docker inspect -f '{{range .HostConfig.Links}}{{.}}{{end}}' "${flow_container_name}") ; do
    if [ "${link: -3}" == "/db" ] ; then
        arr=(${link//:/ })
        db_container_name=${arr[0]}
        db_container_name=${db_container_name:1}
        docker_flags="${docker_flags} --link ${db_container_name}:db"
    fi
done

docker run --rm --volumes-from "${flow_container_name}" ${docker_flags} martinhelmich/flow:dev ./flow $@
